export const ENDPOINTS = {
  CHECK_PHONE: "/student/check-phone",
  LOGIN: "/student/login",
  REGISTER: "/student/register",
  VERIFY_OTP: "/student/verify",
  GET_PROFILE: "/student/info",
  LOGOUT: "/auth/logout",
  MY_PACKAGES: "/student/packages/my-packages",
  GRADE_PACKAGES: "/student/packages",
  SCHEDULE_OF_PACKAGE: "/student/get-group-schedule/",
  GET_MY_SUBSCRIPTIONS: "/student/packages/subscription-packages",
  GROUPS_BY_BACKAGEID: "/student/package-groups",
  CREATE_TRIAL_SUBSCRIPTION: "/student/create-trial-subscription",
  CANCEL_SUBSCRIPTION: "/student/subscriptions/unsubscribe",
  SEND_OTP_CODE: "/student/send-code-for-forget-password",
  VERIFY_OTP_RESET_PASSWORD: "/student/verfiy-code-for-forget-password",
  RESET_PASSWORD: "/student/change-password",
};
