export const MODAL_TYPES = {
  LOGIN: "LOGIN",
  CONFIRM: "CONFIRM",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  WARNING: "WARNING",
  SELECT: "SELECT",
  // Package-related modals
  BUY_PACKAGE: "BUY_PACKAGE",
  DETAILS: "DETAILS",
  CHANGE_GROUP: "CHANGE_GROUP",
  REACTIVATE: "REACTIVATE",
  EXTEND_PACKAGE: "EXTEND_PACKAGE",
};
